packages:
  - packages/*
  - plugins/*
  - modules/*
  - apps/*
  - system/*
  - host/*
  - platform/*

catalog:
  '@iconify-json/ep': ^1.2.3
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.6.0
  element-plus: ^2.11.1
  es-toolkit: ^1.39.8
  less: ^4.4.0
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.4.1
  typescript: ~5.8.3
  unocss: ^66.4.2
  vite: ^7.0.4
  vite-plugin-checker: ^0.10.2
  vite-plugin-dts: ^4.5.4
  vue: ^3.5.17
  vue-i18n: ^11.1.11
  vue-router: ^4.5.1
  vue-tsc: ^2.2.12
